# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e33d073c2bb30462df803556209410664770ebb15801475b12eb9a79992352e794387430adbf629cfbd245f3eefe7b850c80e5c9b4ead3bc8676461ce2639655

test:
  secret_key_base: ba9f4fed4eb5daea484d6b9285cc67a98655603c3cdcfcc48516396269d3fc07b98ea9f6deb2be0f9243eba1998f03b45f5f2fdd3776bbde0de2432bbad36dc0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
